# Generated by Django 4.2.4 on 2023-08-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfsShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('mountPoint', models.CharField(max_length=100)),
                ('Host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Host.host')),
            ],
        ),
    ]
