# Generated by Django 4.2.4 on 2023-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileSystemName', models.CharField(max_length=25)),
                ('NfsShare', models.TextField(null=True, unique=True)),
                ('Host', models.ManyToManyField(to='Host.host')),
            ],
        ),
    ]
