# Generated by Django 4.2.4 on 2023-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
        ('FileSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='Host',
            field=models.ManyToManyField(blank=True, to='Host.host'),
        ),
    ]
