# Generated by Django 4.2.4 on 2023-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
        ('pool', '0007_alter_volumegroup_filesystem'),
        ('FileSystem', '0003_lvfilesystem_delete_filesystem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LvFileSystem',
            new_name='FileSystem',
        ),
    ]
