# Generated by Django 4.2.4 on 2023-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSystem', '0004_rename_lvfilesystem_filesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='lvpath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
