# Generated by Django 4.2.4 on 2023-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSystem', '0005_filesystem_lvpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystem',
            name='Host',
        ),
        migrations.RemoveField(
            model_name='filesystem',
            name='NfsShare',
        ),
        migrations.AlterField(
            model_name='filesystem',
            name='fileSystemName',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
