# Generated by Django 4.2.4 on 2023-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NfsShare', '0001_initial'),
        ('FileSystem', '0006_remove_filesystem_host_remove_filesystem_nfsshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='NfsShare',
            field=models.ManyToManyField(blank=True, to='NfsShare.nfsshare'),
        ),
    ]
