# Generated by Django 4.2.4 on 2023-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Host', '0002_rename_ipaddress_host_ipaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='IpAddress',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
