# Generated by Django 4.2.4 on 2023-08-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeGroup',
            fields=[
                ('PvPath', models.TextField()),
                ('VgName', models.CharField(max_length=30)),
                ('FileSystem', models.TextField(null=True)),
                ('NfsShare', models.TextField(null=True)),
                ('Host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Host.host')),
            ],
        ),
    ]
