# Generated by Django 4.2.4 on 2023-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Host', '0003_alter_host_ipaddress_alter_host_name'),
        ('pool', '0002_delete_volumegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PvPath', models.TextField()),
                ('VgName', models.CharField(max_length=30, unique=True)),
                ('FileSystem', models.TextField(null=True, unique=True)),
                ('NfsShare', models.TextField(null=True, unique=True)),
                ('Host', models.ManyToManyField(to='Host.host')),
            ],
        ),
    ]
