# Generated by Django 4.2.4 on 2023-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSystem', '0001_initial'),
        ('pool', '0005_remove_volumegroup_filesystem_volumegroup_filesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumegroup',
            name='FileSystem',
            field=models.ManyToManyField(blank=True, to='FileSystem.filesystem'),
        ),
    ]
